### ISSUE TITLE
[Campinas/SP ou Maringá/PR] - Projeto internacional (EUA) - Java Back-end Developer na MATERA Systems - Urgente

### ISSUE THREAD

**Issue by dineide** [materasystems/vagas#4]
## Descrição da vaga

Precisamos de Java Back-end developers Jr / Pl / Sr para a MATERA Systems, para atuar com desenvolvimento de back-end microservices com cliente norte-americano. É preciso conseguir se comunicar em inglês.

## Local

- Campinas, São Paulo - Parque II do Polo de Alta Tecnologia;
- Maringá, Paraná - Novo Centro (Zona 07).

## Benefícios

- Horário de trabalho flexível (40h semanais);
- Pacote de Benefícios Flexíveis + PLR (Plano de participação nos lucros e resultados).

## Requisitos

**Obrigatórios:**

- Experiência em desenvolvimento Java/Web;
- Conseguir se comunicar verbalmente em Inglês;
- Disponibilidade para eventuais viagens (nacionais e internacionais);
- Flexibilidade para se adaptar a novas tecnologias.

**Desejáveis:**

- Conhecimento intermediário em RESTful;
- Experiência com Test Driven Development;
- Familiaridade com SVN, Git e com ferramentas como Jira, Confluence, Jenkins e Stash;
- Conhecimento em Scrum.

**Diferencial:**

- Conhecimento de Docker, Kubernetes, Node.js
- Disponibilidade para início imediato.

## Contratação

CLT

## Nossa empresa

A MATERA Systems, desde 1987, atua como fornecedora de soluções e serviços de TI para o mercado financeiro e corporativo, além de realizar o desenvolvimento de aplicativos e projetos. São marcas registradas da empresa investir constantemente em inovação e capacitação de seus profissionais e aliar a excelência técnica ao conhecimento de negócios. Possui mais de 400 profissionais e desde 2008 está no ranking da GPTW. Sedes: Campinas - SP, São Paulo - SP, Niterói - RJ e Maringá - PR.

## Como se candidatar

Por favor envie um email para recrutamento@matera.com com o título desta vaga e seu CV anexo.

**Comment by netstart** [comment]
Look my profile in linkedin: 
https://www.linkedin.com/in/claytonpassos
